// Generated by CoffeeScript 1.4.0

/*
Application default config.
You can override it with config.js file in the root directory.
*/


(function() {

  module.exports = {
    httpPort: 80,
    httpHost: 'localhost'
  };

}).call(this);
