// Generated by CoffeeScript 1.4.0

/*
Add all properties of one object to another

@param {Object} from
@return {Object}
*/


(function() {

  Object.defineProperty(Object.prototype, "extend", {
    enumerable: false,
    value: function(from) {
      var description, name, _i, _len, _ref;
      _ref = Object.getOwnPropertyNames(from);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        name = _ref[_i];
        description = Object.getOwnPropertyDescriptor(from, name);
        Object.defineProperty(this, name, description);
      }
      return this;
    }
  });

}).call(this);
